# For more information: https://laravel.com/docs/sail
services:
  laravel.test:
    build:
      context: "./docker/php"
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP}
        WWWUSER: ${WWWUSER}
        PHP_VERSION: ${PHP_VERSION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "laravel.test:host-gateway"
    environment:
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
      - type: bind
        source: ./docker/php/conf/php.ini
        target: /usr/local/etc/php/conf.d/zzz-custom.ini
      - type: bind
        source: ./docker/php/conf/php-fpm.conf
        target: /usr/local/etc/php-fpm.d/zzz-docker.conf
    working_dir: /var/www/html
    depends_on:
      - mariadb
    networks:
      - sail

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    ports:
      - "${APP_PORT:-80}:8080"
    volumes:
      - ".:/var/www/html:ro"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/templates:/etc/nginx/templates/"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    environment:
      - SERVER=${HOST:-localhost}
    depends_on:
      - laravel.test
    networks:
      - sail

  mariadb:
    image: "mariadb:10"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "sailmariadb:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:mariadb
    ports:
      - 8888:80
    environment:
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_HOST: mariadb
    networks:
      - sail
    depends_on:
      - mariadb

networks:
  sail:
    driver: bridge
volumes:
  sailmariadb:
    driver: local
